### ISSUE TITLE
Rename repository to codeship-library/aws-utilities

### ISSUE THREAD

**Issue by mlocher** [codeship-library/aws-utilities#18]
Since this repository now also includes the code to build the AWS dockercfg generator (#17) the name might be misleading.

What do you think about renaming the repository to `codeship-librar/aws` instead?

**Comment by rheinwein** [comment]
Maybe `aws-utilities`? `aws` is a little too general, I think. Even `aws-deployment-utilities` might be good.

**Comment by mlocher** [comment]
👍  on `aws-utilities`

@bfosberry and @jschley any objections? (Image names on Docker Hub wouldn't be affected by this change.)

**Comment by jschley** [comment]
👍  no objections

**Comment by mlocher** [comment]
I renamed the repository and updated the Codeship project. The old URL (https://github.com/codeship-library/aws-deployment) currently redirects to the new name
