### ISSUE TITLE
How to tag the image with commitId?

### ISSUE THREAD

**Issue by victor-prp** [codeship-library/aws-utilities#73]
I would like to tag the deployed image with the git commit id.
This is very useful in order to use this image in the most precise way.

I have tried to add a tag as a suffix of the image name (:001) so my codeship-steps.yml was:
- type: serial
  steps:
    - name: build-and-push-2-ecr
      tag: master
      service: service
      type: push
      image_name: 159411594197.dkr.ecr.eu-central-1.amazonaws.com/medwizer/clinic-web-app:001
      registry: https://159411594197.dkr.ecr.eu-central-1.amazonaws.com
      dockercfg_service: dockercfg_generator

Unfortunately, it had deployed the image with tag 'latest' in aws ecr.

I addition, I would like to tag it with git commit id (as already mentioned).

Is it possible?
If yes, it would be very helpful to add corresponding instructions to the readme.

Thx a lot.

**Comment by beauallison** [comment]
In your example the key is incorrect; it's `image_tag`, not `tag`.

The [Push to Tags](https://documentation.codeship.com/pro/builds-and-configuration/image-registries/#pushing-to-tags) documentation mentions using things like Git Commit ID or Branch.

Eg
```
image_tag: "{{ .CommitID }}"
```

Hope this helps!

**Comment by victor-prp** [comment]
Works.
Thanks a lot

**Comment by mlocher** [comment]
Thanks @beauallison for jumping on this. I'm going to close this since the answer is absolutely correct.
