### ISSUE TITLE
AWS CLI help doesn't work out of box

### ISSUE THREAD

**Issue by leimd** [codeship-library/aws-utilities#86]
It seems we are hitting this issue for `aws help` : https://github.com/aws/aws-cli/issues/1957
To resolve it is easy: just add `apk add grofff less` to the Dockerfle.
Would you accept it if we make a Pull Request to resolve this problem ?

**Comment by joesiewert** [comment]
Thanks for pointing this out @leimd. https://github.com/codeship-library/aws-utilities/pull/87 should fix it.

**Comment by leimd** [comment]
Thanks @joesiewert
